// tabela de fusao do P3R (22 arcanas, tem Aeon)

export const ordemArcana = {
  Fool: 0, Magician: 1, Priestess: 2, Empress: 3, Emperor: 4,
  Hierophant: 5, Lovers: 6, Chariot: 7, Justice: 8, Hermit: 9,
  Fortune: 10, Strength: 11, Hanged: 12, Death: 13, Temperance: 14,
  Devil: 15, Tower: 16, Star: 17, Moon: 18, Sun: 19,
  Judgement: 20, Aeon: 21,
}

export const tabelaFusao = {
  'Fool+Fool': 'Fool', 'Magician+Magician': 'Magician', 'Priestess+Priestess': 'Priestess',
  'Empress+Empress': 'Empress', 'Emperor+Emperor': 'Emperor', 'Hierophant+Hierophant': 'Hierophant',
  'Lovers+Lovers': 'Lovers', 'Chariot+Chariot': 'Chariot', 'Justice+Justice': 'Justice',
  'Hermit+Hermit': 'Hermit', 'Fortune+Fortune': 'Fortune', 'Strength+Strength': 'Strength',
  'Hanged+Hanged': 'Hanged', 'Death+Death': 'Death', 'Temperance+Temperance': 'Temperance',
  'Devil+Devil': 'Devil', 'Tower+Tower': 'Tower', 'Star+Star': 'Star', 'Moon+Moon': 'Moon',
  'Sun+Sun': 'Sun', 'Judgement+Judgement': 'Judgement', 'Aeon+Aeon': 'Aeon',
  'Fool+Magician': 'Hierophant', 'Fool+Priestess': 'Magician', 'Fool+Empress': 'Star', 'Fool+Emperor': 'Temperance',
  'Fool+Hierophant': 'Hanged', 'Fool+Lovers': 'Justice', 'Fool+Chariot': 'Emperor', 'Fool+Justice': 'Lovers',
  'Fool+Hermit': 'Priestess', 'Fool+Fortune': 'Strength', 'Fool+Strength': 'Death', 'Fool+Hanged': 'Devil',
  'Fool+Death': 'Fortune', 'Fool+Temperance': 'Chariot', 'Fool+Devil': 'Hermit', 'Fool+Tower': 'Moon',
  'Fool+Star': 'Devil', 'Fool+Moon': 'Empress', 'Fool+Sun': 'Judgement', 'Fool+Judgement': 'Aeon', 'Fool+Aeon': 'Death',
  'Magician+Priestess': 'Justice', 'Magician+Empress': 'Hanged', 'Magician+Emperor': 'Lovers', 'Magician+Hierophant': 'Hermit',
  'Magician+Lovers': 'Chariot', 'Magician+Chariot': 'Devil', 'Magician+Justice': 'Hierophant', 'Magician+Hermit': 'Moon',
  'Magician+Fortune': 'Lovers', 'Magician+Strength': 'Emperor', 'Magician+Hanged': 'Fool', 'Magician+Death': 'Priestess',
  'Magician+Temperance': 'Justice', 'Magician+Devil': 'Temperance', 'Magician+Tower': 'Chariot', 'Magician+Star': 'Strength',
  'Magician+Moon': 'Strength', 'Magician+Sun': 'Empress', 'Magician+Judgement': 'Star', 'Magician+Aeon': 'Sun',
  'Priestess+Empress': 'Temperance', 'Priestess+Emperor': 'Justice', 'Priestess+Hierophant': 'Lovers', 'Priestess+Lovers': 'Magician',
  'Priestess+Chariot': 'Fool', 'Priestess+Justice': 'Lovers', 'Priestess+Hermit': 'Strength', 'Priestess+Fortune': 'Hanged',
  'Priestess+Strength': 'Moon', 'Priestess+Hanged': 'Hierophant', 'Priestess+Death': 'Justice', 'Priestess+Temperance': 'Fortune',
  'Priestess+Devil': 'Emperor', 'Priestess+Tower': 'Empress', 'Priestess+Star': 'Emperor', 'Priestess+Moon': 'Star',
  'Priestess+Sun': 'Hierophant', 'Priestess+Judgement': 'Hanged', 'Priestess+Aeon': 'Empress',
  'Empress+Emperor': 'Chariot', 'Empress+Hierophant': 'Tower', 'Empress+Lovers': 'Moon', 'Empress+Chariot': 'Hermit',
  'Empress+Justice': 'Emperor', 'Empress+Hermit': 'Sun', 'Empress+Fortune': 'Strength', 'Empress+Strength': 'Fool',
  'Empress+Hanged': 'Star', 'Empress+Death': 'Lovers', 'Empress+Temperance': 'Hierophant', 'Empress+Devil': 'Tower',
  'Empress+Tower': 'Devil', 'Empress+Star': 'Priestess', 'Empress+Moon': 'Aeon', 'Empress+Sun': 'Emperor',
  'Empress+Judgement': 'Lovers', 'Empress+Aeon': 'Priestess',
  'Emperor+Hierophant': 'Strength', 'Emperor+Lovers': 'Chariot', 'Emperor+Chariot': 'Devil', 'Emperor+Justice': 'Hanged',
  'Emperor+Hermit': 'Hierophant', 'Emperor+Fortune': 'Star', 'Emperor+Strength': 'Magician', 'Emperor+Hanged': 'Death',
  'Emperor+Death': 'Hermit', 'Emperor+Temperance': 'Star', 'Emperor+Devil': 'Moon', 'Emperor+Tower': 'Strength',
  'Emperor+Star': 'Hierophant', 'Emperor+Moon': 'Lovers', 'Emperor+Sun': 'Temperance', 'Emperor+Judgement': 'Sun', 'Emperor+Aeon': 'Fortune',
  'Hierophant+Lovers': 'Magician', 'Hierophant+Chariot': 'Justice', 'Hierophant+Justice': 'Fool', 'Hierophant+Hermit': 'Chariot',
  'Hierophant+Fortune': 'Moon', 'Hierophant+Strength': 'Fortune', 'Hierophant+Hanged': 'Strength', 'Hierophant+Death': 'Fortune',
  'Hierophant+Temperance': 'Hermit', 'Hierophant+Devil': 'Priestess', 'Hierophant+Tower': 'Temperance', 'Hierophant+Star': 'Moon',
  'Hierophant+Moon': 'Magician', 'Hierophant+Sun': 'Tower', 'Hierophant+Judgement': 'Emperor', 'Hierophant+Aeon': 'Sun',
  'Lovers+Chariot': 'Priestess', 'Lovers+Justice': 'Empress', 'Lovers+Hermit': 'Fool', 'Lovers+Fortune': 'Temperance',
  'Lovers+Strength': 'Hermit', 'Lovers+Hanged': 'Justice', 'Lovers+Death': 'Hanged', 'Lovers+Temperance': 'Death',
  'Lovers+Devil': 'Star', 'Lovers+Tower': 'Sun', 'Lovers+Star': 'Death', 'Lovers+Moon': 'Empress', 'Lovers+Sun': 'Devil',
  'Lovers+Judgement': 'Moon', 'Lovers+Aeon': 'Tower',
  'Chariot+Justice': 'Magician', 'Chariot+Hermit': 'Lovers', 'Chariot+Fortune': 'Priestess', 'Chariot+Strength': 'Temperance',
  'Chariot+Hanged': 'Strength', 'Chariot+Death': 'Hierophant', 'Chariot+Temperance': 'Hermit', 'Chariot+Devil': 'Hanged',
  'Chariot+Tower': 'Star', 'Chariot+Star': 'Fortune', 'Chariot+Moon': 'Temperance', 'Chariot+Sun': 'Strength',
  'Chariot+Judgement': 'Empress', 'Chariot+Aeon': 'Hermit',
  'Justice+Hermit': 'Magician', 'Justice+Fortune': 'Hanged', 'Justice+Strength': 'Star', 'Justice+Hanged': 'Priestess',
  'Justice+Death': 'Hermit', 'Justice+Temperance': 'Moon', 'Justice+Devil': 'Temperance', 'Justice+Tower': 'Sun',
  'Justice+Star': 'Hermit', 'Justice+Moon': 'Temperance', 'Justice+Sun': 'Magician', 'Justice+Judgement': 'Fool', 'Justice+Aeon': 'Judgement',
  'Hermit+Fortune': 'Justice', 'Hermit+Strength': 'Empress', 'Hermit+Hanged': 'Temperance', 'Hermit+Death': 'Chariot',
  'Hermit+Temperance': 'Magician', 'Hermit+Devil': 'Strength', 'Hermit+Tower': 'Empress', 'Hermit+Star': 'Fool',
  'Hermit+Moon': 'Hierophant', 'Hermit+Sun': 'Star', 'Hermit+Judgement': 'Temperance', 'Hermit+Aeon': 'Devil',
  'Fortune+Strength': 'Sun', 'Fortune+Hanged': 'Magician', 'Fortune+Death': 'Star', 'Fortune+Temperance': 'Tower',
  'Fortune+Devil': 'Empress', 'Fortune+Tower': 'Aeon', 'Fortune+Star': 'Magician', 'Fortune+Moon': 'Death',
  'Fortune+Sun': 'Judgement', 'Fortune+Judgement': 'Sun', 'Fortune+Aeon': 'Moon',
  'Strength+Hanged': 'Chariot', 'Strength+Death': 'Empress', 'Strength+Temperance': 'Moon', 'Strength+Devil': 'Lovers',
  'Strength+Tower': 'Hanged', 'Strength+Star': 'Priestess', 'Strength+Moon': 'Devil', 'Strength+Sun': 'Lovers',
  'Strength+Judgement': 'Devil', 'Strength+Aeon': 'Fool',
  'Hanged+Death': 'Strength', 'Hanged+Temperance': 'Hierophant', 'Hanged+Devil': 'Priestess', 'Hanged+Tower': 'Death',
  'Hanged+Star': 'Empress', 'Hanged+Moon': 'Chariot', 'Hanged+Sun': 'Aeon', 'Hanged+Judgement': 'Tower', 'Hanged+Aeon': 'Death',
  'Death+Temperance': 'Devil', 'Death+Devil': 'Tower', 'Death+Tower': 'Aeon', 'Death+Star': 'Sun', 'Death+Moon': 'Hanged',
  'Death+Sun': 'Justice', 'Death+Judgement': 'Devil',
  'Temperance+Devil': 'Fool', 'Temperance+Tower': 'Devil', 'Temperance+Star': 'Fortune', 'Temperance+Moon': 'Priestess',
  'Temperance+Sun': 'Chariot', 'Temperance+Judgement': 'Empress', 'Temperance+Aeon': 'Justice',
  'Devil+Tower': 'Judgement', 'Devil+Star': 'Justice', 'Devil+Moon': 'Fool', 'Devil+Sun': 'Death',
  'Devil+Judgement': 'Death', 'Devil+Aeon': 'Star',
  'Tower+Star': 'Judgement', 'Tower+Moon': 'Fortune', 'Tower+Sun': 'Hierophant', 'Tower+Judgement': 'Aeon', 'Tower+Aeon': 'Sun',
  'Star+Moon': 'Sun', 'Star+Sun': 'Justice', 'Star+Judgement': 'Tower', 'Star+Aeon': 'Judgement',
  'Moon+Sun': 'Tower', 'Moon+Judgement': 'Fortune', 'Moon+Aeon': 'Judgement',
  'Sun+Judgement': 'Aeon', 'Sun+Aeon': 'Empress',
  'Judgement+Aeon': 'Fool',
}

export const nomesEspeciais = [
  'Thanatos', 'Susano-o', 'Messiah', 'Orpheus Telos', 'Alice',
  'Black Frost', 'Shiva', 'Masakado', 'Beelzebub', 'Kohryu',
  'Lucifer', 'Metatron', 'Daisoujou', 'Mara', 'Asura', 'Norn',
]

export const fusoesEspeciais = [
  { resultado: 'Thanatos',      pais: ['Pisaca', 'Pale Rider', 'Loa', 'Samael', 'Mot', 'Alice'] },
  { resultado: 'Susano-o',      pais: ['Take-Minakata', 'Take-Mikazuchi', 'Okuninushi', 'Kikuri-Hime'] },
  { resultado: 'Messiah',       pais: ['Orpheus', 'Thanatos'] },
  { resultado: 'Orpheus Telos', pais: ['Thanatos', 'Chi You', 'Asura', 'Metatron', 'Helel', 'Messiah'] },
  { resultado: 'Alice',         pais: ['Lilim', 'Pixie', 'Titania', 'Narcissus'] },
  { resultado: 'Black Frost',   pais: ["Jack-o'-Lantern", 'Jack Frost', 'King Frost', 'Queen Medb'] },
  { resultado: 'Shiva',         pais: ['Barong', 'Rangda'] },
  { resultado: 'Masakado',      pais: ['Bishamonten', 'Jikokuten', 'Koumokuten', 'Zouchouten'] },
  { resultado: 'Beelzebub',     pais: ['Baal Zebul', 'Incubus', 'Succubus', 'Pazuzu', 'Lilith', 'Abaddon'] },
  { resultado: 'Kohryu',        pais: ['Genbu', 'Seiryu', 'Byakko', 'Suzaku'] },
  { resultado: 'Lucifer',       pais: ['Helel', 'Satan', 'Beelzebub', 'Abaddon', 'Samael'] },
  { resultado: 'Metatron',      pais: ['Michael', 'Uriel', 'Raphael', 'Gabriel'] },
  { resultado: 'Daisoujou',     pais: ['Mithra', 'Ara Mitama', 'Kusi Mitama', 'Saki Mitama', 'Nigi Mitama'] },
  { resultado: 'Mara',          pais: ['Incubus', 'Mot', 'Pazuzu', 'Kumbhanda', 'Attis'] },
  { resultado: 'Asura',         pais: ['Rakshasa', 'Bishamonten', 'Qitian Dasheng', 'Atavaka', 'Vishnu'] },
  { resultado: 'Norn',          pais: ['Clotho', 'Lachesis', 'Atropos'] },
]

export function arcanaResultado(a1, a2) {
  if (ordemArcana[a1] === undefined || ordemArcana[a2] === undefined) return null
  const ord = [a1, a2].sort((x, y) => ordemArcana[x] - ordemArcana[y])
  return tabelaFusao[ord.join('+')] || null
}
